name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    services:
      jetstream:
        image: nats:latest
        ports:
          - 4222:4222
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Prepare NATS settings
      run: |
          docker exec ${{ job.services.jetstream.id }} sh -c 'cat /etc/nats/nats-server.conf'
          docker exec ${{ job.services.jetstream.id }} sh -c 'echo "jetstream = enabled" >> /etc/nats/nats-server.conf'
          docker exec ${{ job.services.jetstream.id }} sh -c 'cat /etc/nats/nats-server.conf'
          docker kill --signal=SIGHUP ${{ job.services.jetstream.id }}

    - name: Test
      env:
        NATS_URL: "nats://localhost:4222"
      run: go test -v ./...

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...
