name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    services:
      nats:
        image: nats:alpine
#        ports:
#          - 4222:4222
    steps:
    - name: Prepare NATS settings
      run: |
          docker exec ${{ job.services.jetstream.id }} ash -c 'cat /etc/nats/nats-server.conf'
          docker exec ${{ job.services.jetstream.id }} ash -c 'echo "jetstream = enabled" >> /etc/nats/nats-server.conf'
          docker exec ${{ job.services.jetstream.id }} ash -c 'cat /etc/nats/nats-server.conf'
          docker kill --signal=SIGHUP ${{ job.services.jetstream.id }}
          docker ps

    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Test
      env:
        NATS_URL: "nats://nats:4222"
      run: go test -v ./...

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...
